# Generated by Django 3.0.3 on 2020-02-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
